#!/usr/bin/env bash
# ci-walden tenant-interface v4 — generated by ci-walden tenant-init
# stack: rust (Cargo.toml; native cargo (codegen-verified), else rust:1)
# contract: bash at repo root; exit status is the verdict (0 = green)
# regenerating this file on an unchanged repo is a no-op diff
set -e
if { tmp=/tmp/ci-walden-rustc-probe; printf 'fn main() {}\n' > $tmp.rs && rustc -o $tmp $tmp.rs; rc=$?; rm -f $tmp $tmp.rs; [ $rc -eq 0 ] ; } >/dev/null 2>&1; then
  cargo test
else
  SOCK=""
  if [ -S /var/run/docker.sock ]; then SOCK="-v /var/run/docker.sock:/var/run/docker.sock"; fi
  docker run --rm $SOCK -v "$PWD":/w -w /w rust:1 cargo test
fi
