#!/usr/bin/env bash
# ci-walden tenant-interface v4 — generated by ci-walden tenant-init
# stack: declared (declared entry point (ci-walden/interface.json); the interface calls it and propagates its exit code)
# contract: bash at repo root; exit status is the verdict (0 = green)
# regenerating this file on an unchanged repo is a no-op diff
set -e
echo declared-entry-ran
